# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-science-from-scratch',
                'doc_host': 'https://ronaldlens.github.io',
                'git_url': 'https://github.com/ronaldlens/data-science-from-scratch',
                'lib_path': 'data_science_from_scratch'},
  'syms': { 'data_science_from_scratch.core': { 'data_science_from_scratch.core.foo': ( 'core.html#foo',
                                                                                        'data_science_from_scratch/core.py')}}}
